if (self.CavalryLogger) { CavalryLogger.start_js(["fNR8N"]); }

__d("CometStoryAggregatedUsersSuffixDialogQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3389525257728334",metadata:{relayPreloadable:!0},name:"CometStoryAggregatedUsersSuffixDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometInputWithCommands.react",["CometComponentWithKeyCommands.react","CometKeys","React"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React");function a(a){var c=g.useMemo(function(){var c=[];a.enter!=null&&c.push({command:{key:b("CometKeys").ENTER},description:a.enter.description,handler:a.enter.handler,triggerFromInputs:!0});a["delete"]!=null&&c.push({command:{key:b("CometKeys").DELETE},description:a["delete"].description,handler:a["delete"].handler,triggerFromInputs:!0});a.up!=null&&c.push({command:{key:b("CometKeys").UP},description:a.up.description,handler:a.up.handler,triggerFromInputs:!0});a.down!=null&&c.push({command:{key:b("CometKeys").DOWN},description:a.down.description,handler:a.down.handler,triggerFromInputs:!0});a.tab!=null&&c.push({command:{key:b("CometKeys").TAB},description:a.tab.description,handler:a.tab.handler,triggerFromInputs:!0});a.esc!=null&&c.push({command:{key:b("CometKeys").ESCAPE},description:a.esc.description,handler:a.esc.handler,triggerFromInputs:!0});return c},[a["delete"],a.down,a.enter,a.esc,a.tab,a.up]);return g.jsx(b("CometComponentWithKeyCommands.react"),{commandConfigs:c,debugName:"InputSubmit",elementType:a.isInline===!0?"span":"div",xstyle:a.xstyle,children:a.children})}}),null);
__d("MWChatForceCollapseTabs.bs",["requireCond","cr:1540137"],(function(a,b,c,d,e,f){"use strict";a=b("cr:1540137");c=b("cr:1540137").useHook;f.$Many$chat_heads_plus$MWChatMultiTabForceCollapseTabs$$default$MWChatForceCollapseTabsNoOp$requireCond=b("cr:1540137");f.CollapseTabs=a;f.useHook=c}),null);
__d("MWChatForceCollapseTabs.re",["MWChatForceCollapseTabs.bs"],(function(a,b,c,d,e,f){a=b("MWChatForceCollapseTabs.bs").useHook;f.useHook=a}),null);
__d("MWChatUndoForceCollapseTabs.bs",["requireCond","cr:1540138"],(function(a,b,c,d,e,f){"use strict";a=b("cr:1540138");c=b("cr:1540138").useHook;f.$Many$chat_heads_plus$MWChatMultiTabUndoForceCollapseTabs$$default$MWChatForceCollapseTabsNoOp$requireCond=b("cr:1540138");f.CollapseTabs=a;f.useHook=c}),null);
__d("MWChatUndoForceCollapseTabs.re",["MWChatUndoForceCollapseTabs.bs"],(function(a,b,c,d,e,f){a=b("MWChatUndoForceCollapseTabs.bs").useHook;f.useHook=a}),null);
__d("useToggleChatTabsOnMountUnmount",["CometRouteRenderType","MWChatForceCollapseTabs.re","MWChatUndoForceCollapseTabs.re","React","useShouldShowMessagingEntrypoint"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React");function a(){var a=b("useShouldShowMessagingEntrypoint")("CHAT"),c=b("CometRouteRenderType").useIsPushView(),d=b("MWChatForceCollapseTabs.re").useHook(),e=b("MWChatUndoForceCollapseTabs.re").useHook();g.useEffect(function(){a&&d(c);return function(){a&&e(c)}},[a,c,d,e])}}),null);
__d("CometTextInputWithIcon.react",["BaseTextInput.react","React","TetraIcon.react","stylex"],(function(a,b,c,d,e,f){"use strict";var g,h=b("React"),i={disabledInput:{cursor:"rj84mg9z"},iconEnd:{end:"dpjh1vo5",position:"pmk7jnqg",top:"plgsh5y4"},iconStart:{position:"pmk7jnqg",start:"dnzpfbms",top:"plgsh5y4"},root:{color:"oo9gr5id",fontSize:"jq4qci2q",position:"l9j0dhe7"},textInput:{backgroundColor:"cwj9ozl2",borderTop:"gslguzes",borderEnd:"kigf72y9",borderBottom:"lnt8xvtb",borderStart:"bqd6ffn4",borderTopStartRadius:"ue3kfks5",borderTopEndRadius:"pw54ja7n",borderBottomEndRadius:"uo3d90p7",borderBottomStartRadius:"l82x9zwi",boxSizing:"rq0escxv",color:"oo9gr5id",fontSize:"l94mrbxd",fontWeight:"ekzkrbhg",height:"tv7at329",width:"k4urcfbm"},textInputEndIcon:{paddingTop:"jb3vyjys",paddingEnd:"bowiujrr",paddingBottom:"qt6c0cv9",paddingStart:"h4z51re5"},textInputStartIcon:{paddingTop:"jb3vyjys",paddingEnd:"rv4hoivh",paddingBottom:"qt6c0cv9",paddingStart:"jg4yhqs5"}};function a(a,c){var d=a.disabled;d=d===void 0?!1:d;var e=a.icon,f=a.iconColor,j=a.iconPlacement;j=j===void 0?"start":j;var k=a.label;a=babelHelpers.objectWithoutPropertiesLoose(a,["disabled","icon","iconColor","iconPlacement","label"]);return h.jsxs("div",{className:(g||(g=b("stylex")))(i.root),children:[j==="start"?h.jsx("div",{className:(g||(g=b("stylex")))(i.iconStart),children:h.jsx(b("TetraIcon.react"),{color:f,icon:e,size:16})}):null,h.jsx(b("BaseTextInput.react"),babelHelpers["extends"]({"aria-label":k,disabled:d,xstyle:[d&&i.disabledInput,i.textInput,j==="start"&&i.textInputStartIcon,j==="end"&&i.textInputEndIcon]},a,{ref:c})),j==="end"?h.jsx("div",{className:(g||(g=b("stylex")))(i.iconEnd),children:h.jsx(b("TetraIcon.react"),{color:f,icon:e,size:16})}):null]})}c=h.forwardRef(a);e.exports=c}),null);
__d("CometStoryAggregatedUsersSuffixDialog.entrypoint",["JSResourceForInteraction","WebPixelRatio","CometStoryAggregatedUsersSuffixDialogQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a={getPreloadProps:function(a){var c=a.storyID;a=a.storyRenderLocation;return{queries:{queryReference:{parameters:b("CometStoryAggregatedUsersSuffixDialogQuery$Parameters"),variables:{id:c,renderLocation:a,scale:b("WebPixelRatio").get()}}}}},root:b("JSResourceForInteraction")("CometStoryAggregatedUsersSuffixDialog.react",{"class":"responsive",name:"Comet Aggregated Users Suffix Dialog",oncall:"comet_feed"}).__setRef("CometStoryAggregatedUsersSuffixDialog.entrypoint")};e.exports=a}),null);
__d("CometFeedStorySuffixAggregatedUsersRenderer",["CometEntryPointDialogTrigger.react","CometLink.react","CometStoryAggregatedUsersSuffixDialog.entrypoint","React","recoverableViolation"],(function(a,b,c,d,e,f){"use strict";var g=b("React");a=function(a,c){return function(d){if(a==null||c==null){b("recoverableViolation")("story ID or render location were null when rendering aggregated users link in story title","comet_ui");return d}return g.jsx(b("CometEntryPointDialogTrigger.react"),{dialogEntryPoint:b("CometStoryAggregatedUsersSuffixDialog.entrypoint"),otherProps:{},preloadParams:{storyID:a,storyRenderLocation:c},children:function(a){return g.jsx(b("CometLink.react"),{onClick:a,children:d})}})}};e.exports=a}),null);
__d("validateTrackingCode",[],(function(a,b,c,d,e,f){"use strict";e.exports=a;function a(a){return a!=null&&typeof a==="object"&&a.click_tracking_linkshim_cb!=null&&a.encrypted_click_tracking!=null&&a.encrypted_tracking!=null?a:null}}),null);
__d("validateAggregatedStoryTrackingNodeIndex",[],(function(a,b,c,d,e,f){"use strict";e.exports=a;function a(a){return a!=null&&typeof a==="number"?a:0}}),null);
__d("MWChatForceCollapseTabsNoOp.bs",["React"],(function(a,b,c,d,e,f){"use strict";var g=b("React");function a(a){return g.useCallback(function(a){return 0})}f.useHook=a}),null);
__d("MWChatMultiTabForceCollapseTabs.bs",["bs_block","React","MWChatMultitabContext.bs","MWChatMultitabDispatcher.bs","useCometFeedNoRoutingNavigationEventLogger"],(function(a,b,c,d,e,f){"use strict";var g=b("React");function a(a){var c=b("useCometFeedNoRoutingNavigationEventLogger")(),d=g.useContext(b("MWChatMultitabContext.bs").context);return g.useCallback(function(a){c(Date.now(),"","messenger");if(d!==void 0)return b("MWChatMultitabDispatcher.bs").dispatch(void 0,d,b("bs_block").__(5,[a]));else return 0},[d,c])}f.useHook=a}),null);
__d("MWChatMultiTabUndoForceCollapseTabs.bs",["bs_block","React","MWChatMultitabContext.bs","MWChatMultitabDispatcher.bs","useCometFeedNoRoutingNavigationEventLogger"],(function(a,b,c,d,e,f){"use strict";var g=b("React");function a(a){var c=b("useCometFeedNoRoutingNavigationEventLogger")(),d=g.useContext(b("MWChatMultitabContext.bs").context);return g.useCallback(function(a){c(Date.now(),"","messenger");if(d!==void 0)return b("MWChatMultitabDispatcher.bs").dispatch(void 0,d,b("bs_block").__(6,[a]));else return 0},[d,c])}f.useHook=a}),null);
__d("validatePlayerSuborigin",[],(function(a,b,c,d,e,f){"use strict";e.exports=a;function a(a){return typeof a==="string"?a:null}}),null);